# Generated by Django 5.2.4 on 2025-07-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_member_bith_day_member_email_member_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="bith_day",
        ),
        migrations.AddField(
            model_name="member",
            name="birthday",
            field=models.DateField(null=True),
        ),
    ]
